const quotes = {    
    one: {
        SFW: [
            { quote: "{A}: DoorLung!<br /><span class='fx'>*squelch*</span><br />{A}: Only the choicest organs on DoorLung!<br /><span class='fx'>*plop*</span>", quoter: ["Bob"], source: "<cite>Hair</cite>, Episode 1, Distractible" },
            { quote: "{A}: I do not care how they smell. If clowns are parachuting into my city, I am fucking OUT.", quoter: ["Bob"], source: "<cite>Body Odor</cite>, Episode 2, Distractible" },
            { quote: "<span class='desc'>On their second vaccination...</span><br />{A}: I don't know what I'm gonna do, but it's—it feels like <strong>freedom</strong>.<br />{A}: It's gonna be hard to resist the urge to just go lick strangers on the street, because...I'm immune, bitches!", quoter: ["Bob"], source: "<cite>Conventions</cite>, Episode 8, Distractible" },
            { quote: "<span class='desc'>{A} drives back home after sneaking out at midnight to go on a movie date with a girl called Smithers...</span><br />{A}: And then—part of my perfect planning—I drive back home, and I fill up the gas tank perfectly 'cause I remembered exactly where it was.<br />{A}: I thought <em>desperately</em> about how to roll back the odometer to make sure that it wasn't—any indication that I was out that night, because of course, I thought my dad would check, first thing in the morning, what the odometer was, or even remember.<br />{A}: So, I, like, snuck it into the driveway.<br />{A}: I...retrace my steps, going back through the gravel path, and into the sliding door, which I had left unlocked, sneak up to my room, and I—just look at the note that I wrote?<br />{A}: And—it was the stupidest note, because it said something like:<br />{A}: <span class='letter'>Dad,</span> comma...<br />{A}: <span class='letter'>I know you're probably worried about me...</span><br />{A}: <span class='letter'>but don't be! I snuck out, and I—to go see, like, Smithers at the movie theater.</span><br />{A}: <span class='letter'>I know you probably think less of me for this, but just know...</span><br />{A}: <span class='letter'>I did it for love!</span><br />{A}: <span class='letter'>Signed—</span>I think I wrote—<span class='letter'>Sincerely, {A}</span>.", quoter: ["Mark"], source: "<cite>Perfect Crime</cite>, Episode 11, Distractible" },
            { quote: "<span class='desc'>{A} knocks on some random stranger's house...</span><br />{A}: This shit is either going on your doorstep or in your toilet. Please choose!", quoter: ["Bob"], source: "<cite>Oh Sh*t Moments</cite>, Episode 16, Distractible" },
        ],
        NSFW: [
            
        ],
    },
    two: {
        SFW: [
            { quote: "{B}: Okay, but imagine, like, you get paid minimum wage, but PER ORGAN, right?<br />{B}: So y-you just take on, like, ten organs—you're making good money.<br />{B}: You're making REAL good money!<br />{A}: There's no way it would be that fair. Somehow—somehow, the rich people who were paying these organ-growing humans would find a way to make it a tipped profession.", quoter: ["Bob", "Mark"], source: "<cite>Hair</cite>, Episode 1, Distractible" },
            { quote: "{B}: Would you like me to go first, {A}?<br />{A}: You—I've got—well, hey, let's debate about who should go first. That's—that's really the key here—<br />{B}: Ah, <em>debatable</em>, our new podcast.", quoter: ["Mark", "Wade"], source: "<cite>Transportation</cite>, Episode 3, Distractible" },
            { quote: "{A}: I'm already willing to accept that the earth is a living, breathing creature that was fucked into existence by Jupiter and Mars, and maybe Pluto—<br />{A}: I-I've somehow agreed to all of that.<br />{A}: The teleportation thing? I'm just having a little bit of trouble understanding it. I just—I'm just struggling a bit on that...<br />{B}:<br />{B}: Well, listen, I'm no scientist, but...<br />{B}: From my understanding of how things are gonna work ten thousand years from now, uh, I mean, I'm pretty sure we'll know—by then?<br />{A}:<br />{A}: Ten <em>thousand</em> years! 10,000?!<br />{B}: Maybe it's ten years?<br />{A}: TEN?!<br />{A}: THAT'S A BIG RANGE!", quoter: ["Mark", "Wade"], source: "<cite>Transportation</cite>, Episode 3, Distractible" },
            { quote: "{A}: Oh, I got questions. You want questions? I got questions.<br />{B}: By all means.<br />{A}: Well, well, well. If we're giving out bonus points...<br />{A}: How long...is both your legs together<br />{A}: and<br />{A}: why do I need to know that?<br />{B}:<br />{A}: You don't get to know the answer to that one. That's a question for <em>me</em>.", quoter: ["Bob", "Wade"], source: "<cite>Camping</cite>, Episode 4, Distractible" },
            { quote: "<span class='fx'>*Inspirational music starts playing*</span><br />{A}: I don't know if I've said this to you guys, but I've always thought that <strong>inspiration</strong> is, like, the most valuable thing you can give to people. Like, above almost everything else in terms of humanity. The reason, like, landing people on the moon—not even just Americans—but, like, landing people on the moon was so important—like, from a cost perspective, from a practicality perspective—yeah, sure, there's science and stuff—but, like, for everyone's day-to-day life, it doesn't really affect it. But the <em>moment</em> the <em>footage</em> of people seeing that <em>someone landed on the moon</em>—that changed an entire generation's perspective of what was even possible! Like, the—<br />{B}: I thought that was fake! <span class='parenthetical'>*laughing*</span><br />{A}: —don't get this started, man, I'll fuckin'—I'll destroy you! I'LL DESTROY YOUUU—", quoter: ["Mark", "Wade"], source: "<cite>Fake Tech</cite>, Episode 5, Distractible" },
            { quote: "{A}: Careful what you lick in a hotel room, that's all I'm sayin'.<br />{B}: You know me—I lick every corner of the room, I have to.<br />{A}: Yeah.<br/>{B}: As soon as I walk into a room.<br/>{A}: 's how it feels like home. It's how you adjust.", quoter: ["Bob", "Mark"], source: "<cite>Bob's Fridge</cite>, Episode 7, Distractible" },
            { quote: "{B}: Can you imagine if 9-1-1 had an automated system like that?<br />{B}: <span class='electronic'>\"For class-one emergencies, press 1!\ For class-two emergencies, press 2!\"</span><br />{B}: <span class='electronic'>\"Stay on the line if this is a major emergency!\"</span><br />{A}: <span class='electronic'>\"What's your problem?\"</span> I'M BLEEEEDING!<br />{A}: <span class='electronic'>\"Bo-bo-bo-boop! Connecting you to...\"</span><br/>{B}: <span class='electronic'>\"For bleeding, try calling 9-1-1, and your extension will be 6-7-9-4-2!\"</span>", quoter: ["Mark", "Wade"], source: "<cite>Bob's Fridge</cite>, Episode 7, Distractible" },
            { quote: "{A}: I didn't even fucking look. I didn't have GPS, I didn't have printed-out MapQuest directions or anything. I just was like \"Yeah, I know where that is!\" and went.<br />{A}: Which I can't imagine doing right now. As an adult—and I know where things are—who does that?<br />{A}: I would never do that!<br />{A}:<br />{A}: You do that, {B}, actually, yeah, don't you?<br />{B}: Yeah. Of course I do.<br />{A}: Fuckin' psychopath.<br />{B}: What do you mean?<br />{A}: What if you go the wrong way?<br />{B}: Well, what if I don't go the wrong way <br />{A}: What if you think of the wrong thing?<br />{B}: NAW, I know the way!<br />{A}: What if you drive an hour in the wrong direction?!<br />{B}: I look at the STARS—I guide my way.", quoter: ["Bob", "Mark"], source: "<cite>Hold My Beer</cite>, Episode 9, Distractible" },
            { quote: "{B}: <span class='electronic'>On June 17th, {A} awoke at 6:30 AM! SIX-THIRTY!!</span><br />{B}: <span class='electronic'>Why? We'll find out why he wasn't sleeping that well that night.</span><br />{B}: <span class='electronic'>BED NEWS, coming to you live!</span><br />{A}: I mean, I do get up at 5:45 in the morning, so...<br />{B}: <span class='parenthetical'>*gasp*</span> Therefore, you were awake—oh my god, I predicted the past!", quoter: ["Mark", "Wade"], source: "<cite>Perfect Crime</cite>, Episode 11, Distractible" },
            { quote: "{A}: It was<br />{A}: I<br />{A}: I could not...stop my body from expelling that stuff.<br />{B}: <span class='parenthetical'>*wheezing*</span><br />{A}: I've never experienced that before! I'm an adult, and I'm like—I've been in situations where I couldn't go to the bathroom for <em>hours</em>. And I just sit there, and you're just like \"Yeah, well, it's kinda... This hurts. My stomach really hurts, but I'll be fine. I'll make it to the ba—\"<br />{A}: <span class='parenthetical'>*deep breath in*</span><br />{A}: That was like—I was battling a demon—<br />{A}: and I <em>lost</em><br />{A}: —and it <em>killed me</em>!<br />{B}: <span class='parenthetical'>*laughing*</span> And then it put me back together, after it scooped out everything within me, and placed it on the walls!<br />{A}: I walked out of that Quik Stop bathroom a husk of a human—<br />{B}: <span class='parenthetical'>*laughing even harder*</span><br />{A}: —so dehydrated that I nearly deflated!", quoter: ["Bob", "Mark"], source: "<cite>Oh Sh*t Moments</cite>, Episode 16, Distractible" },
            { quote: "<span class='desc'>{B} and {A} are trading \"How Dare You\" stories...</span><br />{B}: Alright, {A}, what about you? For—more opportunities where you have been wronged or you wronged others.<br />{A}: I mean, this is kinda low-hanging fruit, but I...worked on a lotta food service jobs...<br />{B}: Uh-huh...<br />{A}: Aaand let me tell you...<br />{A}: Fuck anyone who has ever bought a sandwich from me at the Jimmy John's that I worked at.", quoter: ["Bob", "Mark"], source: "<cite>How Dare You</cite>, Episode 17, Distractible" },
            { quote: "<span class='desc'>{A} is recounting their work experiences at Jimmy John's...</span><br />{A}: Ignoring the motivations, assuming someone's just absolutely drunk off their mind... how do you do that without getting it all over yourself? Which is the more terrifying part to me!<br />{A}: It's a skill—it's an adult skill to learn how to use a bathroom, and, y'know, keep everything clean, make sure you wash your hands, make sure that everything when you're done in the bathroom is nice and tidy...<br />{A}: Kids aren't good at that.<br />{B}: W-Well, what if that's the thing, what if they've never been taught?<br />{B}: What if every time that person walks in to the bathroom, they're just sweating bullets, because they're going, like, \"Alright, trying...attempt number 328,\" and they just <i>shotgun-blast</i> poop all over the walls, and they're, like, \"Okay! That didn't wor—\"<br />{A}: Don't eat at Jimmy John's, you dumb piece of shit!", quoter: ["Bob", "Mark"], source: "<cite>How Dare You</cite>, Episode 17, Distractible" },
            { quote: "{A}: This can be broadly-applied to society, but this gives me big fuck-you energy every day of my life I go in public.<br />{A}: But especially at the restaurant.<br />{A}: Who...fucking...raised you...<br />{A}: that you can't be bothered...to crumple up the piece of paper that your sandwich came in—<br />{A}: and <i>lift</i> that heavy, empty paper cup that your drink came in...<br />{A}: And DROP 'em in the TRASHCAN that's NEXT to the door you walk out of when you leave!?<br />{A}: What the hell kinda animals are we raising in this country—people are so shitty about trash, about putting the cart back at the grocery store—<br />{A}: What the fuck is wrong with you people?!<br /><span class='desc'>Later...</span><br />{A}: Humanity—doesn't deserve to exist.<br />{A}: I've changed my perspective.<br />{A}: Just from reminding myself about <em>these</em> facts about our society.<br />{A}: We don't deserve it!<br />{B}: This is what retail does to us.", quoter: ["Bob", "Wade"], source: "<cite>How Dare You</cite>, Episode 17, Distractible" },
            { quote: "{B}: I'll grab a couple dumbbells. I was doing, like, some different things where I'd, like, y'know, stay in there and watch TV, and I'd be like...<br />{A}:<br />{B}: twisting and lifting and sitting up and all of that stuff—<br />{A}: <span class='parenthetical'>*wheezing</span> Oh, I thought that was the end of it. I was gonna have to break it to you that <em>that's</em> not working out, {B}.", quoter: ["Bob", "Wade"], source: "<cite>Life Plan</cite>, Episode 20, Distractible" },
        ],
        NSFW: [            
        ],
    },
    three: {
        SFW: [
            { quote: "{C}: Did I say \"ways to remove unwanted hair\"? Today's episode is \"ways to add WANTED hair\"!<br />{B}: Can we get, like, add OR remove—or transplant—or just shift around—<br />{C}: Y'know what, ways to HAIR! Sure.<br />{A}: Ways to change the amount of hair on places on you! <br />{C}: Whatever you want to do with hair, we will talk about it today.<br />{B}: ...Yeah, but why? Why would you want to remove hair?<br />{B}: Hair is beautiful~<br/><span class='fx'>*twinkly-shimmery sounds*</span><br />{C}: ...Well, maybe you have a severe hair-phobia, and you just really wanna <b>[BLEEEEEEEP]</b>, so you give 'em a heads up. They gotta get rid of that stuff...<br />{B}:<br />{A}:<br />{C}:<br />{C}: OR<br />{C}: OTHER REASONS!!! MAYBE YOU'RE A SWIMMER?", quoter: ["Bob", "Mark", "Wade"], source: "<cite>Hair</cite>, Episode 1, Distractible" },
            { quote: "{B}: Okay, back up, back up, back up, back up...<br />{B}: The earth is a living, breathing <em>being</em> is what you're saying?<br />{C}: Yeah, why do you think volcanoes erupt? Earth's, like, \"UGHHHHH. Damn it, mom,\" y'know?<br />{B}: Who is earth's mom—wait, hold on!<br />{C}: Oh, uh, y'know, Mother... Jupiter, and Father—<br />{C}: fuck you<br />{C}: —uh, Mars?<br />{A}: <i>Wha</i>—How are you mad about this?! You—you—this is <em>your</em> story!", quoter: ["Bob", "Mark", "Wade"], source: "<cite>Transportation</cite>, Episode 3, Distractible" },
            { quote: "{B}: {C}, I got—I got one more question for you.<br />{C}: Oh, boy.<br />{B}: <span class='parenthetical'>*ominously*</span> Do you wanna go camping with me?<br />{C}: I cautiously am saying yes...<br />{B}: <span class='parenthetical'>*ominously*</span> Excellent... Okay, good...<br />{A}: <span class='parenthetical'>*whispering*</span> That feels like a mistake.<br />{C}: I think so, too, but curiosity gets the best of me sometimes.<br />{A}: What are you? A cat?<br />{C}: AWW, GEE-WHIZ, <span class='UPPERCASE'>{C}</span>, what have you got yerself into this time...<br />{A}:<br />{B}:<br />{C}:<br />{A}:<br />{B}:<br />{C}:<br />{C}: Um.<br />{A}:<br />{B}:<br />{C}: UH, SO—", quoter: ["Bob", "Mark", "Wade"], source: "<cite>Camping</cite>, Episode 4, Distractible" },
            { quote: "{B}: For those at home who don't know about Dashcon, Dashcon is—uh, well, it <em>was</em> the Tumblr convention. It was supposed to be a fan convention.<br />{B}: And I-I didn't even know about this, but the name Dashcon? I thought it was a brony convention.<br />{A}: Ehh.<br />{B}: I think, I think there's a—there's a—there's a pony called, like, Dash—<br />{C}: Dashy-do?<br />{A}: Dashy-do—that's the one, yeah.<br />{B}: Yeah, Dashy-do. We all know...Dashy... Is that actually...?<br />{A}: Yeah, everybody knows Dashy-do. I love Dashy-do.<br />{B}: Is that actually, is—that actually the name? Dashy-do?<br />{A}: Yes, don't look it up.", quoter: ["Bob", "Mark", "Wade"], source: "<cite>Conventions</cite>, Episode 8, Distractible" },
            { quote: "{A}: How...are you? How is your time on...<br />{A}: l-l-living...going?<br />{B}:<br />{B}: Man... Uh, ye—uh—good? You alright, man?<br />{A}: Yeah, I'm fine!<br />{C}: Better before you worded the question like that, I think.<br />{C}: Now, I'm a little concerned about my time living.<br />{A}: Well, you gotta enjoy it while you're still alive, right?<br />{A}: Are you enjoyin' it?", quoter: ["Bob", "Mark", "Wade"], source: "<cite>Perfect Crime</cite>, Episode 11, Distractible" },
            { quote: "{A}: This week's prompt is... \"What is your perfect crime?\"<br />{B}: Mm...<br />{A}: I feel like—I have this. I think most people have this. I'm sure you've thought of, like—maybe you had a job or...there was some situation where you had some knowledge or access to something, and you were like:<br />{A}: <span class='thought'>You know what? I am the one person in the <em>world</em> where I could do this, I could steal this thing, or I could do this one thing and get away with it.</span><br />{A}: <span class='thought'>No one would ever suspect me, and I can pull it off perfectly.</span><br />{B}:<br />{C}: To be clear, this is a crime we would do, not one we have already gotten away with?<br />{B}:<br />{A}: Yeah, don't describe past acts. This is a new, theoretical crime—<br />{B}: I <em>just</em> googled what the statute of limitations is.", quoter: ["Bob", "Mark", "Wade"], source: "<cite>Perfect Crime</cite>, Episode 11, Distractible" },
            { quote: "{A}: Has there ever been a person, like, genetically-anomalously good at healing?<br />{C}: Wolverine!<br />{A}: Kinda like a natural Wolverine—thing?<br />{B}: A real person.<br />{A}: Like a real person.<br />{C}: Hugh Jackman... <span class='parenthetical'>*laughing*</span> He plays Wolverine.<br />{A}:<br />{A}: Oh, you mean Deadpool.", quoter: ["Bob", "Mark", "Wade"], source: "<cite>Happy Funerals</cite>, Episode 13, Distractible" },
            { quote: "<span class='desc'>On the topic of \"Happy Funerals\"...</span><br />{A}: <span class='parenthetical'>*sigh*</span><br />{C}: ...What're we talking about? Death! Yeah.<br />{C}: I don't know. I don't care. Don't care about me. When I'm dead, I'm just dead.<br />{C}: <span class='parenthetical'>*chuckling*</span> Fuck off. Leave me alone.<br />{A}: God, jeez!<br />{B}: <span class='parenthetical'>*guffawing*</span><br />{C}: I dealt with you all in life, don't let me deal with your tears!<br />{A}: Holy shit, I'm <em>sorry</em> I brought it up!<br />{B}: Oh my god—<br />{C}: I survived you, you survived me. Move on!<br />{B}: Oh my god.<br />{C}: There's more people out there, talk to them! Jesus.<br />{C}: Make a new friend!", quoter: ["Bob", "Mark", "Wade"], source: "<cite>Happy Funerals</cite>, Episode 13, Distractible" },
            { quote: "<span class='desc'>On the topic of \"How To Make A Best Friend\"...</span><br />{C}: You find a sneaky way to get that phone number, right? You get the phone number. You call. They answer:<br />Best friend: <span class='electronic'>Hello?</span><br />{C}: <span class='electronic'>*heavy breathing*</span><br />Best friend: <span class='electronic'>W-Who is this?!</span><br />{C}: Click.<br />{A}: Wow.<br />{B}: Da—da—damn, man.<br />{C}: They're wondering:<br />Best friend: <span class='thought'>Could it be that guy who made eye contact? Oh, god. How did he get my number?</span><br />{C}: And the fear starts to set in, which is perfect!", quoter: ["Bob", "Mark", "Wade"], source: "<cite>How To Make A Best Friend</cite>, Episode 15, Distractible" },
            { quote: "<span class='desc'>After staring at, harassing, and creeping someone out...</span><br />{C}: Step one's accomplished. You got it in, baby.<br />{C}: Step two: <b>Face to Face</b>.<br /><span class='desc'>Later...</span><br />{C}: And then you come in, you greet 'em, you talk to 'em. If they <em>react poorly</em>, you leave. Maybe for days, maybe for weeks, maybe months. Bring 'em food, keep 'em alive. You have to make sure that they appreciate the time you get together.<br />{C}: And over the course of, again, months—years, even—they'll appreciate your friendship so much, that...<br />{C}: They'll realize you're their only friend.<br />{C}: And if not, there's always, like, I don't know, waterboarding or...electrocution, or something. Y'know, there are ways to convince them...of your friendship.<br />{C}: But eventually, they're broken, they've got no one in life but you, and you've got a friend for life...<br />{B}:<br />{B}: Was that...step two?<br />{A}: That was all step two.<br />{B}: That was all step two... Okay, cool, cool.", quoter: ["Bob", "Mark", "Wade"], source: "<cite>How To Make A Best Friend</cite>, Episode 15, Distractible" },
            { quote: "{B}: Today's topic that we're going to be talking about, {A} and {C}, is titled, so simply: \"How Fucking Dare You\".<br />{B}: And in this, we are going to be reliving situations where someone has <em>wronged</em> us—maybe we've wronged someone. I will accept that as well, because you can also be the one that fucking dares.<br />{B}: Uh, but I will accept stories with which you guys have been wronged, and your rage for this has never left your bodies.<br />{C}: So, like, uh, revenge, comeuppance, that kinda thing?<br />{B}: Yeah. Anything like that.<br />{C}: If you wrong somebody that wronged you, are you really wronging them? Tha—is it—two wrongs make a right, right?<br />{B}: Uhh...<br />{B}: We are not qualified to answer that question in this episode. We will answer that in the future.<br />{A}: <span class='parenthetical'>*deadpan*</span> I believe two wrongs make a...wro-wrongongong.<br />{C}: <span class='parenthetical'>*chortling*</span><br />{B}: I—", quoter: ["Bob", "Mark", "Wade"], source: "<cite>How Dare You</cite>, Episode 17, Distractible" },
            { quote: "{C}: Welcome back to Distractible, starring me, your host, {C}.<br />{C}: I got {B} and {A} here as well. Howdy, guys.<br />{B}: Hello, hello, hello...<br />{A}: Not starring. Just here. Just some guy.<br />{B}: Yeah. <i>Just a guest.</i><br />{B}: Guest starring? Guest star.<br/ >{C}: Starring me, the host—<br />{B}: Mm-hm.<br />{C}: —and guesting you two!<br />{A}: Featuring? Featuring us?<br />{B}: Featuring? Yeah?<br />{C}: Ehhhhh, that sounds more important than I'd like you to sound.<br />{A}: And ALSO—us?<br />{B}: {C} and friends...?<br />{C}: {C} and acquaintances!", quoter: ["Bob", "Mark", "Wade"], source: "<cite>Dreams & Nightmares</cite>, Episode 18, Distractible" },
            { quote: "<span class='desc'>Host {C} joins in on {B} and {A} talking about childhood dreams...</span><br />{C}: I guess to throw <em>my</em> ring in the hat with the first one that I remember—<br />{B}: Ring in the hat?<br />{C}: My hat in the ring?<br >{B}: Theeere you go.<br />{C}: Ring in the hat—y'know, you throw your ring in the hat.<br />{B}: Yeah, you throw your ring in the hat and hat in the ring? You put the ring in the hat?<br />{C}: Yeah. You—well, you can have a hat and throw it in a ring, but if you have a <em>smaller</em> ring, you can throw it in the hat.<br />{B}: Throw it in the hat, but then what happens when you throw a ring in the hat and your hat in the ring?<br />{A}: Well, then, get a ring in the ring-hat!<br />{C}: Well, it's like putting a rabbit in the hat, you can find and put a rabbit in the hat to pull a rabbit out of the hat, y'know?<br />{B}: Yeah, y—what if you put a ring on the rabbit in the hat? And you pull that out. Which do you pull up: the ring or the rabbit?<br />{C}: Uh, depends. What if the rabbit's wearing the ring?<br />{B}:<br />{B}: That's what I just said—the ring was on the rabbit. Rabbit was wearing the ring.<br />{C}: Then, I guess you pull out both.<br/ >{B}: But which one goes first...?<br />{C}: Uhh, guess it depends on what part of the r—if you're grabbin' the rabbit by the ears, where's the rabbit wearing the ring?<br />{B}: <span class='parenthetical'>*inhale*</span><br />{B}: You got me there, deduct points.<br />{C}: From...myself?<br />{A}: Are there points?", quoter: ["Bob", "Mark", "Wade"], source: "<cite>Dreams & Nightmares</cite>, Episode 18, Distractible" },
            { quote: "{B}: I feel like sometimes I wake up in an alternate reality and it's like everything is exactly the same except my hair is slightly curlier<br />{B}: and then, y'know, there's prolly some other things that I'm not noticing, but—<br />{A}: Dude, I get that but with my teeth.<br />{C}: Your teeth get curly?<br />{A}: You ever get that? You ever get curly teeth?<br />{B}: NO?? WHAT???<br />{A}: Aw, me either.", quoter: ["Bob", "Mark", "Wade"], source: "<cite>Saving You Money!</cite>, Episode 245, Distractible" },
        ],
        NSFW: [
            { quote: "<span class='desc'>{A} and {C} are trying to score points in the story title category: \"Seasons Don't Fear The Reaper, They Fear The Titties\" versus \"Milford Chainsaw Massacre\"</span><br />{A}: Look, maybe my story is garbage, maybe all I have is the title. Don't concede yet, {C}.<br />{C}: I got a good story! I'm just sayin' the title—I just, y'know, I-I changed one word in the title—from another—I guess you took—<br />{C}: You used a song lyric, I stole another movie. We—We both suck. But yours is—you suck better.<br />{A}: I suck reaaal good.<br />{B}: ...God, you guys are really trying to win this one!", quoter: ["Bob", "Mark", "Wade"], source: "<cite>Supernatural</cite>, Episode 6, Distractible" },
            { quote: "{A}: It's just an old fridge. It's not like—I'm not saying anything about the person who lived here before us, but, the water that came out of it, the ice, the food...it just had a stank!<br />{A}: Clearly didn't fix it. The baking soda and the—thing didnt fix it.<br />{A}: So we got a new one.<br />{A}: And like, that's pretty exciting. New fridge is exciting. You know no one has stored their dog's semen in it before.<br />{B}: <span class='parenthetical'>*sputtering*</span><br />{C}: That is a very specific...qualification.<br />{A}: I'm NOT saying that I know I've lived in a house with a fridge where there was dog semen stored in it.<br />{A}: I'm just saying, if you live in a rental especially, <em>you don't know what was in that fridge before</em>.", quoter: ["Bob", "Mark", "Wade"], source: "<cite>Bob's Fridge</cite>, Episode 7, Distractible" },
            { quote: "{C}: I can't get my penis hard!<br />{B}: I don't—what does that mean? I can't get—what does that mean?<br />{A}: Is it the bald thing? Is this a—is this, like, a metaphor for being bald?<br />{C}: No, no—LITERALLY—erection. Help.<br />{B}:<br />{A}: You need to stop and ask for erections?", quoter: ["Bob", "Mark", "Wade"], source: "<cite>Hold My Beer</cite>, Episode 9, Distractible" },
            { quote: "{B}: So, today, I have a topic of conversation I think everyone at home can identify with and, uh, can understand—<br />{C}: Genital warts?<br />{B}: —and the topic of today<br />{B}:<br />{B}: What?<br />{C}: Nothing. Go ahead.<br />{B}: You wanna say that again?<br />{C}: Uh, general worries?<br />{A}: I believe he said \"genital warts\".<br />{B}: *ominously* I believe you said \"genital warts\".<br />{C}: You guys are just hearing what you wanna hear...", quoter: ["Bob", "Mark", "Wade"], source: "<cite>Lies From Parents</cite>, Episode 21, Distractible" },
        ],
    },
};